### ISSUE TITLE
Upload to WebDAV errors 

### ISSUE THREAD

**Issue by srevinsaju** [TheAssassin/pyuploadtool#1]
Related to https://github.com/TheAssassin/prebuilt-cmake/runs/1539252185?check_suite_focus=true, I do not have good knowledge about WebDAV, but perhaps, its an error specific to the secret which is set?

```
2020-12-11 19:11:13,225 pyuploadtool.releases-hosting-provider-factory [INFO] guessing releases hosting provider from environment variables
2020-12-11 19:11:13,225 pyuploadtool.releases-hosting-provider-factory [INFO] detected WebDAV
2020-12-11 19:11:13,226 pyuploadtool.releases-hosting-provider-factory [INFO] detected GitHub releases
2020-12-11 19:11:13,226 pyuploadtool.cli [INFO] available release hosting providers: WebDAV, GitHub Releases
2020-12-11 19:11:13,226 pyuploadtool.cli [INFO] creating release on hosting provider WebDAV
2020-12-11 19:11:13,226 pyuploadtool.webdav [INFO] using user-specified release name ""
2020-12-11 19:11:13,226 pyuploadtool.webdav [INFO] uploading artifact "centos7-i386.zip/cmake-v3.19.1-centos7-i386.tar.gz"
Traceback (most recent call last):
  File "/tmp/.mount_pyuplo8gcHwk/usr/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_pyuplo8gcHwk/usr/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_pyuplo8gcHwk/usr/conda/lib/python3.8/site-packages/pyuploadtool/__main__.py", line 69, in <module>
    provider.create_release(metadata, artifacts)
  File "/tmp/.mount_pyuplo8gcHwk/usr/conda/lib/python3.8/site-packages/pyuploadtool/releases_hosting_provider/webdav.py", line 69, in create_release
    response = self.requests_session.put(artifact_url, data=f)
  File "/tmp/.mount_pyuplo8gcHwk/usr/conda/lib/python3.8/site-packages/requests/sessions.py", line 590, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/tmp/.mount_pyuplo8gcHwk/usr/conda/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/tmp/.mount_pyuplo8gcHwk/usr/conda/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
    p.prepare(
  File "/tmp/.mount_pyuplo8gcHwk/usr/conda/lib/python3.8/site-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/tmp/.mount_pyuplo8gcHwk/usr/conda/lib/python3.8/site-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/cmake-v3.19.1-centos7-i386.tar.gz': No schema supplied. Perhaps you meant http:///cmake-v3.19.1-centos7-i386.tar.gz?
```

**Comment by srevinsaju** [comment]
Fixed

**Comment by TheAssassin** [comment]
Well, "fixed" isn't very descriptive. The reason it failed was because in PRs, secrets are not available, so `${{ secrets.SOME_VAR }}` will evaluate as an empty string. If you set environment variables to those expressions, you will have empty environment variables.

The tool should not attempt to upload PR builds anyway. Hence, I introduced "build types" as a metadata type, made sure to recognize PRs properly, and disabled uploads for those in both the WebDAV and GitHub releases hosting provider implementations (i.e., display a warning and return immediately). This'll prevent this issue in the future.
